version: "3.7"

services:
    mongodb:
        image: mongo
        container_name: mongo-linkapi-test
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - 27017:27017
        volumes:
            - pgdata:/data/mongodg

volumes:
    pgdata:
        driver: local